// AmericaPulse.live — Shared App Engine

const SECTION_COLORS = {
  politics:'#C8102E', business:'#0B6E4F', technology:'#2563EB',
  sports:'#EA580C', health:'#7C3AED', world:'#0891B2',
  entertainment:'#DB2777', opinion:'#92400E'
};
const SECTION_ICONS = {
  politics:'🏛️', business:'📈', technology:'💻',
  sports:'🏆', health:'🏥', world:'🌐',
  entertainment:'🎬', opinion:'✍️'
};
function sectionLabel(s) {
  return `${SECTION_ICONS[s] || '📰'} ${capitalize(s)}`;
}

// ---- Utilities ----
function formatDate(dateStr) {
  const d = new Date(dateStr + 'T12:00:00');
  return d.toLocaleDateString('en-US', { year:'numeric', month:'long', day:'numeric' });
}
function timeAgo(dateStr) {
  const now = new Date();
  const then = new Date(dateStr + 'T12:00:00');
  const diff = Math.floor((now - then) / 1000);
  if (diff < 3600)  return `${Math.floor(diff/60)}m ago`;
  if (diff < 86400) return `${Math.floor(diff/3600)}h ago`;
  const days = Math.floor(diff/86400);
  if (days < 7) return `${days}d ago`;
  return formatDate(dateStr);
}
function capitalize(s) { return s.charAt(0).toUpperCase() + s.slice(1); }
function goArticle(slug) { window.location.href = `article.html?slug=${slug}`; }

// ---- Sort newest first ----
function sortByDate(arr) {
  return [...arr].sort((a, b) => new Date(b.date) - new Date(a.date));
}

// ---- Fetch AI/RSS articles from Netlify function ----
async function fetchLiveArticles(section, limit = 16) {
  try {
    const url = section
      ? `/.netlify/functions/get-articles?section=${section}&limit=${limit}`
      : `/.netlify/functions/get-articles?limit=${limit}`;
    const r = await fetch(url);
    if (r.ok) { const d = await r.json(); return d.articles || []; }
  } catch(e) {}
  return [];
}

// ---- Merge static + live, newest first, no slug duplicates ----
function mergeArticles(staticArts, liveArts) {
  const seen = new Set();
  const merged = [];
  for (const a of [...liveArts, ...staticArts]) {
    if (!seen.has(a.slug)) { seen.add(a.slug); merged.push(a); }
  }
  return sortByDate(merged);
}

// ---- Article card HTML ----
function renderCard(article, size = 'sm') {
  const color = SECTION_COLORS[article.section] || '#C8102E';
  const badge = article.autoGenerated
    ? `<span class="rss-badge" title="Auto-fetched from RSS">LIVE</span>` : '';
  if (size === 'lg') {
    return `
    <article class="news-card card-featured" onclick="goArticle('${article.slug}')" style="cursor:pointer">
      <div class="card-img-wrap">
        <img src="${article.image}" alt="${article.title}" loading="lazy" />
        ${badge}
      </div>
      <div class="card-body">
        <span class="card-tag" style="background:${color}">${sectionLabel(article.section)}</span>
        <h3 class="card-title">${article.title}</h3>
        <p class="card-excerpt">${article.excerpt}</p>
        <div class="card-meta">
          <span>${article.author}</span>
          <time>${formatDate(article.date)}</time>
          <span>${article.readTime || 5} min read</span>
        </div>
      </div>
    </article>`;
  }
  return `
  <article class="news-card-sm" onclick="goArticle('${article.slug}')" style="cursor:pointer">
    <div class="card-img-wrap">
      <img src="${article.image}" alt="${article.title}" loading="lazy" />
      ${badge}
    </div>
    <div class="card-body">
      <span class="card-tag" style="background:${color}">${capitalize(article.section)}</span>
      <h3 class="card-title-sm">${article.title}</h3>
      <div class="card-meta">
        <span>${article.author}</span>
        <time title="${formatDate(article.date)}">${timeAgo(article.date)}</time>
      </div>
    </div>
  </article>`;
}

function renderListItem(article) {
  const color = SECTION_COLORS[article.section] || '#C8102E';
  const badge = article.autoGenerated
    ? `<span class="rss-badge">LIVE</span>` : '';
  return `
  <article class="news-list-item" onclick="goArticle('${article.slug}')" style="cursor:pointer">
    <div class="list-img"><img src="${article.image}" alt="${article.title}" loading="lazy" /></div>
    <div class="list-body">
      <span class="card-tag" style="background:${color}">${capitalize(article.section)}</span>
      ${badge}
      <h4>${article.title}</h4>
      <time title="${formatDate(article.date)}">${timeAgo(article.date)}</time>
    </div>
  </article>`;
}

// ---- Section page renderer (async — merges live + static, newest first) ----
async function renderSectionPage(sectionId) {
  const container = document.getElementById('section-articles');
  if (!container) return;
  container.innerHTML = '<p class="loading-msg">Loading latest stories…</p>';

  const color = SECTION_COLORS[sectionId];

  // Fetch live articles, merge with static, sort newest first
  const liveArts  = await fetchLiveArticles(sectionId, 10);
  const staticArts = getArticlesBySection(sectionId);
  const articles   = mergeArticles(staticArts, liveArts);

  if (!articles.length) {
    container.innerHTML = '<p class="no-articles">No articles yet. Check back soon.</p>';
    return;
  }

  const [feat, second, third, ...rest] = articles;

  let html = `<div class="hero-lead" style="margin-bottom:32px">
    <div class="hero-card hero-main" onclick="goArticle('${feat.slug}')" style="cursor:pointer">
      <div class="hero-img-wrap">
        <img src="${feat.image}" alt="${feat.title}" loading="eager"/>
        <span class="hero-category-tag" style="background:${color}">${sectionLabel(sectionId)}</span>
        ${feat.autoGenerated ? '<span class="rss-badge hero-live">LIVE</span>' : ''}
      </div>
      <div class="hero-body">
        <h1 class="hero-title">${feat.title}</h1>
        <p class="hero-excerpt">${feat.excerpt}</p>
        <div class="hero-meta">
          <span class="author">${feat.author}</span>
          <span class="dot">•</span>
          <time>${formatDate(feat.date)}</time>
          <span class="dot">•</span>
          <span>${feat.readTime||5} min read</span>
        </div>
      </div>
    </div>
    <div class="hero-side">
      ${[second, third].filter(Boolean).map(a => `
      <div class="hero-card hero-secondary" onclick="goArticle('${a.slug}')" style="cursor:pointer">
        <div class="hero-img-wrap">
          <img src="${a.image}" alt="${a.title}" loading="lazy"/>
          <span class="hero-category-tag" style="background:${color}">${sectionLabel(sectionId)}</span>
          ${a.autoGenerated ? '<span class="rss-badge">LIVE</span>' : ''}
        </div>
        <div class="hero-body">
          <h2 class="hero-title-sm">${a.title}</h2>
          <div class="hero-meta">
            <span class="author">${a.author}</span>
            <span class="dot">•</span>
            <time>${timeAgo(a.date)}</time>
          </div>
        </div>
      </div>`).join('')}
    </div>
  </div>`;

  // Archive grid — all remaining, newest first
  if (rest.length) {
    html += `
    <div class="section-header" style="margin-bottom:20px">
      <h2 class="section-title"><span class="section-accent" style="background:${color}">${capitalize(sectionId)} Archive</span></h2>
      <span class="article-count">${articles.length} stories</span>
    </div>
    <div class="cards-row four-col" style="margin-bottom:32px">
      ${rest.map(a => renderCard(a, 'sm')).join('')}
    </div>`;
  }

  container.innerHTML = html;
}

// ---- Article detail page ----
async function renderArticlePage() {
  const params  = new URLSearchParams(window.location.search);
  const slug    = params.get('slug');
  if (!slug) { window.location.href = 'index.html'; return; }

  let article = getArticleBySlug(slug);

  if (!article) {
    try {
      const r = await fetch(`/.netlify/functions/get-articles?slug=${encodeURIComponent(slug)}`);
      if (r.ok) { const d = await r.json(); article = d.article || null; }
    } catch(e) {}
  }

  const el = document.getElementById('article-content');
  if (!article) {
    el.innerHTML = '<p class="no-articles">Article not found. <a href="index.html">← Home</a></p>';
    return;
  }

  const color = SECTION_COLORS[article.section] || '#C8102E';
  document.title = `${article.title} — AmericaPulse.live`;

  const sourceLine = article.sourceName
    ? `<a href="${article.sourceUrl||'#'}" target="_blank" rel="noopener" class="source-link">Source: ${article.sourceName}</a>`
    : '';

  el.innerHTML = `
    <div class="article-header">
      <div class="article-breadcrumb">
        <a href="index.html">Home</a> /
        <a href="${article.section}.html">${capitalize(article.section)}</a>
      </div>
      <span class="card-tag" style="background:${color}">${capitalize(article.section)}</span>
      ${article.autoGenerated ? '<span class="rss-badge" style="margin-left:8px">LIVE RSS</span>' : ''}
      <h1 class="article-title">${article.title}</h1>
      <p class="article-excerpt">${article.excerpt}</p>
      <div class="article-meta">
        <span class="author-meta">By <strong>${article.author}</strong></span>
        <span class="dot">•</span>
        <time>${formatDate(article.date)}</time>
        <span class="dot">•</span>
        <span>${article.readTime||5} min read</span>
        ${sourceLine}
      </div>
    </div>
    <div class="article-hero-img">
      <img src="${article.image}" alt="${article.title}" />
    </div>
    <div class="article-body">${article.body}</div>
    <div class="article-tags">
      ${(article.tags||[]).map(t => `<span class="article-tag">${t}</span>`).join('')}
    </div>`;

  // Related articles — same section, newest first, exclude current
  const liveRelated  = await fetchLiveArticles(article.section, 6);
  const staticRelated = getArticlesBySection(article.section).filter(a => a.slug !== slug);
  const related = mergeArticles(staticRelated, liveRelated.filter(a => a.slug !== slug)).slice(0, 4);

  if (related.length) {
    const relEl = document.getElementById('related-articles');
    if (relEl) {
      relEl.innerHTML = `
        <div class="section-header">
          <h2 class="section-title"><span class="section-accent" style="background:${color}">More in ${capitalize(article.section)}</span></h2>
        </div>
        <div class="cards-row four-col">${related.map(a => renderCard(a,'sm')).join('')}</div>`;
    }
  }
}

// ---- Trending sidebar (newest first) ----
async function renderTrending(containerId) {
  const el = document.getElementById(containerId);
  if (!el) return;

  // Static articles sorted newest first
  const staticArts = getAllArticles(8);
  el.innerHTML = staticArts.map((a, i) => `
    <li>
      <span class="trend-num">${String(i+1).padStart(2,'0')}</span>
      <div class="trend-body">
        <a href="article.html?slug=${a.slug}">${a.title}</a>
        <time>${timeAgo(a.date)}</time>
      </div>
    </li>`).join('');

  // Prepend live RSS articles if available
  try {
    const r = await fetch('/.netlify/functions/get-articles?limit=3');
    if (r.ok) {
      const d = await r.json();
      if (d.articles && d.articles.length) {
        const liveHtml = d.articles.map(a => `
          <li class="ai-generated">
            <span class="trend-num ai-badge">LIVE</span>
            <div class="trend-body">
              <a href="article.html?slug=${a.slug}">${a.title}</a>
              <time>${timeAgo(a.date)} • ${a.sourceName || 'RSS'}</time>
            </div>
          </li>`).join('');
        el.insertAdjacentHTML('afterbegin', liveHtml);
      }
    }
  } catch(e) {}
}
